Update tripal_biomaterial_loader_v3.inc
Fixing error loading tsv and csv Biosamples

1. Change the validation isset into !empty:

The value set by default in $values['file_local'], $values['file_upload'] and $values['file_upload_existing'] is NULL, so the isset will consider the statement as TRUE.

2. Change the function to print the error log in the function test_biosample_cvterms_flat:

When the flat file was not found in the server or when there are not samples in the flat file, the system prints an error message in the log, however when it attempts to call the function logMessage it generates the following error:

Error: Using $this when not in object context in test_biosample_cvterms_flat() (line 1039 of /var/www/html/sites/all/modules/tripal_analysis_expression/tripal_biomaterial/includes/TripalImporter/tripal_biomaterial_loader_v3.inc
To fix this bug I print the error message in the log by means of the function error_log instead of logMessage

3. Read the attributes and values of the flat file and set them into the attributes_list in a consistent format:

Firstly I declared a variable to determine the number of the row containing the header: $nLineHeader
The values in attribute list is initialized empty: $attribute_list["values"] = [];
Set only one value "attributes" in the attributes list, which contains the unique headers: $attribute_list["attributes"][$header] = $header;
Fill the unique values into the attribute_list array from lines in the flat file, starting from the next line after the header.